apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress
  annotations:
    ingress.kubernetes.io/rewrite-target: /
    ingress.kubernetes.io/proxy-body-size: 2000m
spec:
  rules:
  - host: registry.invalid
    http:
      paths:
      - path: /
        backend:
          serviceName: {{ .Values.dockerRegistryDns }}
          servicePort: 5000
  - host: influxdb.invalid
    http:
      paths:
      - path: /
        backend:
          serviceName: {{ .Values.dockerInfluxDbDns }}
          servicePort: 8086
  - host: concourse.invalid
    http:
      paths:
      - path: /
        backend:
          serviceName: {{ .Release.Name }}-web
          servicePort: 8080

  - host: minio.invalid
    http:
      paths:
      - path: /
        backend:
          serviceName: {{ .Values.dockerMinioDns }}
          servicePort: 9000

  - host: local-npm.invalid
    http:
      paths:
      - path: /
        backend:
          serviceName: {{ .Values.dockerLocalNpmDns }}
          servicePort: 5080
